# Template: https://github.com/pypa/sampleproject/blob/main/pyproject.toml

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "easymesh"
version = "0.1.0"
description = "A simple and efficient async mesh network library"
authors = [
    { name = "Austin Bowen", email = "austin.bowen.314@example.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "psutil",
]

[project.optional-dependencies]
test = []

[project.urls]
"Homepage" = "https://github.com/austin-bowen/easymesh"
"Source" = "https://github.com/austin-bowen/easymesh"
"Bug Reports" = "https://github.com/austin-bowen/easymesh/issues"
