[tool.poetry]
name = "easymesh"
version = "0.1.0"
description = "Simple, fast inter-process message passing for distributed Python processes"
authors = ["Austin Bowen <austin.bowen.314@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
